spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/talondatabase?autoReconnect=true&useSSL=false&characterEncoding=utf8&useUnicode=true
    username: root
    password: root
server:
  port: 8080

spring-hoc:
  cors:
    allow-credentials: true
    allowed-origins:
      - "https://my-frontend-application.com"
      - "https://jpomykala.com"
      - "http://localhost"
    allowed-methods:
      - GET
      - POST
      - PATCH
      - DELETE